name: emb3rs-market-module
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ampl-mp=3.1.0
  - blas=1.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - colorama=0.4.4
  - cppad=20210000.6
  - cvxpy=1.1.17
  - cvxpy-base=1.1.17
  - cycler=0.10.0
  - dbus=1.13.18
  - ecos=2.0.7.post1
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - ipopt=3.14.4
  - jpeg=9d
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - metis=5.1.0
  - mumps-include=5.2.1
  - mumps-seq=5.2.1
  - munkres=1.1.4
  - ncurses=6.3
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1l
  - osqp=0.6.2.post0
  - pandas=1.3.4
  - pcre=8.45
  - pillow=8.4.0
  - pip=21.2.4
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyscipopt=3.4.0
  - python=3.8.12
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2021.3
  - qdldl-python=0.1.5
  - qt=5.9.7
  - readline=8.1
  - scip=7.0.3
  - scipy=1.7.2
  - scotch=6.0.9
  - scs=3.0.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - sqlite=3.36.0
  - tbb=2020.2
  - tk=8.6.11
  - tornado=6.1
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
